version: "1"
invalidStatus: "pending"
labelRule:
  values:
    - "bug"
    - "documentation"
    - "internal-improvement"
    - "performance"
    - "dependencies"
    - "feature"
    - "breaking-change"
    - "skip-changelog"
