name: Release Notes

on:
  push:
    branches:
      - main

jobs:
  update_draft_release:
    if: github.repository == 'larq/compute-engine'
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
